Fix a bug in octree.to_points()
octree-nn/ocnn-pytorch pull request #38
Opened 2024-08-30 16:33 UTC by sh8

Hi!

Thank you so much for the great work! I fixed a bug in octree.to_points() which does not rescale correctly when self.points[self.depth] is None. Could you please check the code and merge it if this change looks good to you?

Thanks!

2024-09-02 13:14 UTC, wang-ps commented
Thanks for figuring out this issue!  I could not understand the purpose of the first line of modifictions. Please see my comments above.

2024-09-03 04:55 UTC, sh8 commented
Since `self.xyzb(depth, nempty=True)` gives unnormalized points in the range of [0, 2^d] so you have to rescale it to obtain correct xyz. I think that overriding the rescale argument is a bit ugly, but less confusing for users.

2024-09-03 13:34 UTC, wang-ps requested changes
I think Line 497 should be deleted. Because self.points[depth] is also in [0, 2^d)

2024-09-03 19:25 UTC, sh8 commented
Yes, you're right! I deleted L.497 accordingly

2024-09-04 00:12 UTC, merged

2024-09-04 00:13 UTC, wang-ps commented
Thank you so much @sh8 , I have merged the pull request.